# Generated by Django 2.1.15 on 2020-04-26 01:41

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('PN', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('part_type', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fleet', models.CharField(max_length=255)),
                ('ata', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('PN', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('part_type', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fleet', models.CharField(max_length=255)),
                ('ata', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='avref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_sysid', models.FloatField()),
                ('p_part_nam', models.CharField(max_length=255)),
                ('oldPN', models.CharField(max_length=255)),
                ('PN', models.CharField(max_length=255)),
                ('p_cage', models.CharField(max_length=255)),
                ('p_nsn', models.CharField(max_length=255)),
                ('p_description', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_condit', models.CharField(max_length=255)),
                ('part_type', models.CharField(max_length=255)),
                ('p_update', models.DateField(default=datetime.date.today)),
                ('p_unit', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ILSQH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('PO_Number', models.FloatField()),
                ('PN', models.CharField(max_length=255)),
                ('Provided_Description', models.CharField(max_length=255)),
                ('Stripped_part_Number', models.CharField(max_length=255)),
                ('Quote_Description', models.CharField(max_length=255)),
                ('Condition', models.CharField(max_length=255)),
                ('Quantity', models.FloatField()),
                ('Quote_Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('UM', models.CharField(max_length=255)),
                ('Exchange', models.CharField(max_length=255)),
                ('Quote_Date', models.DateField(default=datetime.date.today)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SatairList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('PN', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('part_type', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fleet', models.CharField(max_length=255)),
                ('ata', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='spiInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('PN', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('part_type', models.CharField(max_length=255)),
                ('cond', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fleet', models.CharField(max_length=255)),
                ('ata', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=255)),
                ('Serialized', models.CharField(max_length=255)),
                ('LLP', models.CharField(max_length=255)),
                ('Effectivity', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
