# Generated by Django 2.1.15 on 2020-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avref',
            old_name='p_description',
            new_name='p_descript',
        ),
        migrations.RenameField(
            model_name='avref',
            old_name='part_type',
            new_name='part_Type',
        ),
    ]
