# Generated by Django 2.1.15 on 2020-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiapps', '0004_auto_20200514_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avref',
            old_name='part_Type',
            new_name='p_Type',
        ),
        migrations.RemoveField(
            model_name='avref',
            name='id',
        ),
        migrations.AlterField(
            model_name='avref',
            name='p_sysid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
