# Generated by Django 2.1.15 on 2020-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiapps', '0005_auto_20200514_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afhs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='airlines',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ilsqh',
            name='id',
        ),
        migrations.RemoveField(
            model_name='satairlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='afhs',
            name='PN',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='PN',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ilsqh',
            name='PN',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satairlist',
            name='PN',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spiinv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
