# Generated by Django 2.1.15 on 2020-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiapps', '0006_auto_20200516_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiinv',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
